inherit_gem:
  rubocop-g2:
    - config/ruby/default.yml

require:
  - rubocop-rspec
  - rubocop-g2

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - gemfiles/*

Style/Documentation:
  Enabled: false
