version: 2.1

orbs:
  ruby: g2crowd/ruby@0.0.13

workflows:
  version: 2
  build:
    jobs:
      - ruby/appraisal:
          context: g2crowd-global
          matrix:
            parameters:
              ruby: ['2.6.8', '2.7.4', '3.0.2']
              appraisal:
                - rails_5.1
                - rails_5.2
                - rails_6.0
                - rails_6.1
            exclude:
              - ruby: '3.0.2'
                appraisal: rails_5.1
              - ruby: '3.0.2'
                appraisal: rails_5.2
              - ruby: '3.0.2'
                appraisal: rails_6.0
      - ruby/build:
          context: g2crowd-global
          setup-database: false
          bundler-version: '2.1.4'
