version: 2.1

orbs:
  ruby: g2crowd/ruby@0.1.0

workflows:
  version: 2
  build:
    jobs:
      - ruby/appraisal:
          context: g2crowd-global
          matrix:
            parameters:
              ruby: ['2.7.5', '3.0.3']
              appraisal:
                - rails_6.0
                - rails_6.1
                - rails_7.0
            exclude:
              - ruby: '3.0.3'
                appraisal: rails_6.0
      - ruby/build:
          context: g2crowd-global
          ruby: '3.0.3'
          setup-database: false
          bundler-version: '2.2.32'
