name: Ruby CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.7.8', '3.0.7', '3.1.6', '3.2.5']
        appraisal: ['rails_6.1', 'rails_7.0', 'rails_7.1']
    steps:
      - uses: actions/checkout@v7
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: '2.3.10'
      - name: Install dependencies
        run: |
          bundle install
      - name: Install appraisal dependencies
        run: bundle exec appraisal install
      - name: Run appraisal
        run: bundle exec appraisal ${{ matrix.appraisal }} rspec
